name: Deploy Hugo site to Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo (extended)
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.121.2'
          extended: true

      # Utwórz minimalne pliki, jeśli nie istnieją
      - name: Ensure minimal Hugo site (if missing)
        run: |
          mkdir -p config/_d_
