name: Deploy Hugo site to Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree (debug)
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type f | sort

      - name: Setup Hugo (extended)
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.121.2'
          extended: true

      - name: Ensure minimal Hugo site (if missing)
        run: |
          set -e
          # config
          if [ ! -f config.toml ] && [ ! -f config/_default/hugo.toml ]; then
            mkdir -p config/_default
            cat > config/_default/hugo.toml << 'EOF'
baseURL = 'https://ratm23.g
